# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
