# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0002_auto_20170429_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
