# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0004_auto_20170429_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='corresponding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collabtool.InstitutionAuthor'),
        ),
    ]
