# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0005_auto_20170429_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='corresponding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='collabtool.InstitutionAuthor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collabtool.Venue'),
        ),
    ]
