# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0006_auto_20170429_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(null=True, to='collabtool.InstitutionAuthor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='corresponding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collabtool.InstitutionAuthor'),
        ),
    ]
