# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0007_auto_20170429_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(to='collabtool.InstitutionAuthor'),
        ),
    ]
