# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0010_auto_20170430_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_protected',
            field=models.BooleanField(default=False),
        ),
    ]
