# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0011_project_data_protected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Paper',
        ),
    ]
