# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0014_auto_20170827_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userperms',
            old_name='usr_paper_access',
            new_name='paper_access',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='code',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='data',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='data_protected',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pa_code_access',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pa_data_access',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pa_paper_access',
        ),
        migrations.RemoveField(
            model_name='userperms',
            name='usr_code_access',
        ),
        migrations.RemoveField(
            model_name='userperms',
            name='usr_data_access',
        ),
        migrations.RemoveField(
            model_name='userperms',
            name='usr_project_access',
        ),
        migrations.RemoveField(
            model_name='userperms',
            name='usr_whitepaper_access',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='code',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='data',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='wp_code_access',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='wp_data_access',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='wp_paper_access',
        ),
        migrations.AddField(
            model_name='code',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=b'data/'),
        ),
        migrations.AddField(
            model_name='data',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.ManyToManyField(to='collabtool.Code'),
        ),
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.ManyToManyField(to='collabtool.Data'),
        ),
        migrations.AddField(
            model_name='project',
            name='paper',
            field=models.ManyToManyField(to='collabtool.Paper'),
        ),
        migrations.AddField(
            model_name='project',
            name='whitepaper',
            field=models.ManyToManyField(to='collabtool.WhitePaper'),
        ),
        migrations.AddField(
            model_name='userperms',
            name='code_access',
            field=models.ManyToManyField(blank=True, related_name='can_access_code', to='collabtool.Code'),
        ),
        migrations.AddField(
            model_name='userperms',
            name='data',
            field=models.ManyToManyField(to='collabtool.Data'),
        ),
        migrations.AddField(
            model_name='userperms',
            name='data_access',
            field=models.ManyToManyField(blank=True, related_name='can_access_data', to='collabtool.Data'),
        ),
        migrations.AddField(
            model_name='userperms',
            name='project_access',
            field=models.ManyToManyField(blank=True, related_name='can_access_project', to='collabtool.Project'),
        ),
        migrations.AddField(
            model_name='userperms',
            name='whitepaper_access',
            field=models.ManyToManyField(blank=True, related_name='can_access_whitepaper', to='collabtool.WhitePaper'),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='code_protected',
            field=models.BooleanField(default=False),
        ),
    ]
