# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0018_auto_20170831_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'data'},
        ),
        migrations.AlterModelOptions(
            name='groupaccess',
            options={'verbose_name_plural': 'group accesses'},
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='code_protected',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='data_protected',
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
