# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0023_auto_20170915_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name_plural': 'code'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='wiki',
        ),
    ]
