# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0024_auto_20170918_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group_access',
            field=models.ManyToManyField(blank=True, related_name='project_group_accesses', to='collabtool.GroupAccess'),
        ),
    ]
