# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collabtool', '0025_auto_20170926_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('abstract', models.TextField()),
                ('paper', models.FileField(blank=True, null=True, upload_to=b'paper/')),
                ('url', models.URLField(blank=True, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='collabtool.InstitutionAuthor')),
                ('corresponding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collabtool.InstitutionAuthor')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collabtool.Venue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='group_access',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group_access',
        ),
        migrations.RemoveField(
            model_name='project',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='project',
            name='whitepaper',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='group_access',
        ),
        migrations.AddField(
            model_name='project',
            name='publication',
            field=models.ManyToManyField(blank=True, to='collabtool.Publication'),
        ),
    ]
