# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0027_auto_20170927_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='group_access',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='group_access',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='group_access',
        ),
        migrations.AddField(
            model_name='publication',
            name='group_access',
            field=models.ManyToManyField(to='collabtool.GroupAccess'),
        ),
    ]
