# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-30 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0028_auto_20170927_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='d_hash',
            field=models.CharField(default=b'', max_length=128, null=True),
        ),
    ]
