# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-30 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0029_data_d_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='d_hash',
            new_name='f_hash',
        ),
    ]
