# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-30 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0030_auto_20170930_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='f_hash',
            new_name='sha512',
        ),
        migrations.RemoveField(
            model_name='code',
            name='code',
        ),
        migrations.RemoveField(
            model_name='code',
            name='group_access',
        ),
        migrations.RemoveField(
            model_name='code',
            name='protected',
        ),
        migrations.RemoveField(
            model_name='data',
            name='group_access',
        ),
        migrations.RemoveField(
            model_name='data',
            name='protected',
        ),
        migrations.AddField(
            model_name='code',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=b'data/'),
        ),
        migrations.AddField(
            model_name='code',
            name='sha512',
            field=models.CharField(default=b'', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.ManyToManyField(blank=True, related_name='project_code', to='collabtool.Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.ManyToManyField(blank=True, related_name='project_data', to='collabtool.Data'),
        ),
    ]
