# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0031_auto_20170930_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='group_access',
            field=models.ManyToManyField(to='collabtool.GroupAccess'),
        ),
        migrations.AddField(
            model_name='data',
            name='group_access',
            field=models.ManyToManyField(to='collabtool.GroupAccess'),
        ),
    ]
