# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0032_auto_20170930_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='group_access',
            field=models.ManyToManyField(to='collabtool.GroupAccess'),
        ),
        migrations.AddField(
            model_name='paper',
            name='group_access',
            field=models.ManyToManyField(to='collabtool.GroupAccess'),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='group_access',
            field=models.ManyToManyField(to='collabtool.GroupAccess'),
        ),
    ]
