# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0033_auto_20170930_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='anonymous_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='anonymous_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='anonymous_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='anonymous_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='anonymous_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='anonymous_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='anonymous_access',
            field=models.BooleanField(default=False),
        ),
    ]
