# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0034_auto_20170930_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='whitepaper',
            name='paper',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=b'data/'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='sha512',
            field=models.CharField(default=b'', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=b'data/'),
        ),
        migrations.AddField(
            model_name='paper',
            name='sha512',
            field=models.CharField(default=b'', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=b'data/'),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='sha512',
            field=models.CharField(default=b'', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='slug',
            field=models.SlugField(default=b'', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='title',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(default=b'', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='slug',
            field=models.SlugField(default=b'', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='title',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
