# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0036_auto_20171001_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='date',
            field=models.DateField(),
        ),
    ]
