# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0037_auto_20171001_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='abstract',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='authors',
            field=models.ManyToManyField(blank=True, to='collabtool.InstitutionAuthor'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collabtool.Venue'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, to='collabtool.InstitutionAuthor'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collabtool.Venue'),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='abstract',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='authors',
            field=models.ManyToManyField(blank=True, to='collabtool.InstitutionAuthor'),
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collabtool.Venue'),
        ),
    ]
