# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0038_auto_20171001_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='data',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='data',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='deliverable',
            old_name='data',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='data',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='whitepaper',
            old_name='data',
            new_name='file',
        ),
    ]
