# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0039_auto_20171001_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhitePaper',
            new_name='Report',
        ),
    ]
