# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0040_auto_20171001_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionauthor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='institutionauthor',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collabtool.Institution'),
        ),
    ]
