# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0041_auto_20171001_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='data',
            field=models.ManyToManyField(blank=True, to='collabtool.Data'),
        ),
        migrations.AddField(
            model_name='paper',
            name='data',
            field=models.ManyToManyField(blank=True, to='collabtool.Data'),
        ),
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.ManyToManyField(blank=True, to='collabtool.Data'),
        ),
    ]
