# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0042_auto_20171002_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='code',
            field=models.ManyToManyField(blank=True, to='collabtool.Code'),
        ),
        migrations.AddField(
            model_name='paper',
            name='code',
            field=models.ManyToManyField(blank=True, to='collabtool.Code'),
        ),
        migrations.AddField(
            model_name='report',
            name='code',
            field=models.ManyToManyField(blank=True, to='collabtool.Code'),
        ),
    ]
