# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0044_auto_20171004_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='collabtool.Author'),
        ),
    ]
