# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0047_auto_20171004_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='anonymous_access',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='group_access',
        ),
    ]
