# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0049_vulnerability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='collabtool_deliverable', to='collabtool.InstitutionAuthor'),
        ),
        migrations.AlterField(
            model_name='institutionauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabtool.Author'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='collabtool_paper', to='collabtool.InstitutionAuthor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.ManyToManyField(blank=True, to='collabtool.Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.ManyToManyField(blank=True, to='collabtool.Data'),
        ),
        migrations.AlterField(
            model_name='report',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='collabtool_report', to='collabtool.InstitutionAuthor'),
        ),
    ]
