# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0050_auto_20171005_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[(b'2', b'accepted'), (b'0', b'draft'), (b'3', b'published'), (b'1', b'submitted')], default=3, max_length=1),
        ),
    ]
