# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0051_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name=b'DOI'),
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, help_text=b'Only for a book.', max_length=32, null=True, unique=True, verbose_name=b'ISBN'),
        ),
    ]
