# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0052_auto_20171005_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='status',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='doi',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name=b'DOI'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='isbn',
            field=models.CharField(blank=True, help_text=b'Only for a book.', max_length=32, null=True, unique=True, verbose_name=b'ISBN'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[(b'2', b'accepted'), (b'0', b'draft'), (b'3', b'published'), (b'1', b'submitted')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name=b'DOI'),
        ),
        migrations.AddField(
            model_name='paper',
            name='isbn',
            field=models.CharField(blank=True, help_text=b'Only for a book.', max_length=32, null=True, unique=True, verbose_name=b'ISBN'),
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[(b'2', b'accepted'), (b'0', b'draft'), (b'3', b'published'), (b'1', b'submitted')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='report',
            name='doi',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name=b'DOI'),
        ),
        migrations.AddField(
            model_name='report',
            name='isbn',
            field=models.CharField(blank=True, help_text=b'Only for a book.', max_length=32, null=True, unique=True, verbose_name=b'ISBN'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[(b'2', b'accepted'), (b'0', b'draft'), (b'3', b'published'), (b'1', b'submitted')], default=3, max_length=1),
        ),
    ]
