# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabtool', '0053_auto_20171005_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='tags',
            field=models.CharField(blank=True, help_text=b'List of tags separated by commas.', max_length=256),
        ),
        migrations.AddField(
            model_name='paper',
            name='tags',
            field=models.CharField(blank=True, help_text=b'List of tags separated by commas.', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text=b'List of tags separated by commas.', max_length=256),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, help_text=b'List of tags separated by commas.', max_length=256),
        ),
    ]
