# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collabtool', '0056_delete_vulnerability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
